### PR TITLE
ISSUE-81: Export/import metadata Displays script using JSON API and JQ

### LINKED ISSUE #81: Export/import metadata Displays script using JSON API and JQ
# What?

Using the JSON:API, `jq` and some bash/sh tooling we need to build one scripts that can
1.- Export all Metadata Displays from JSON:API, clean, remove fixed fields and create one file per metadata display
2.- Generates a reingest script (similar to our `update_deployed.sh`) that can be used then to ingest somewhere else those metadata entities.

 I started working and based on my simple proto-idea @aksm provided this

```Shell
curl -w "\n" --user jsonapi:****** -H 'Accept: application/vnd.api+json' \
-H 'Content-type: application/vnd.api+json' \ 
-XGET 'http://localhost:8001/jsonapi/metadatadisplay_entity/metadatadisplay_entity' \
 | jq -cr '.data[]|del(.relationships)|del(.attributes.created)|del(.attributes.drupal_internal__id)|del(.attributes.changed)|del(.attributes.link)| \{"data": .}'| awk -F'\t' '{ i++ ; fname = "metadatadisplay_entity_" i ".json"; print > fname; close(fname)}'
```

### PR DESCRIPTION
**Pull request by aksm**
Starts to resolve #81 

The script is functional for import/export but will need work, improvements, testing, and documentation. Currently it's able to export to the directory from which it's run or optionally any provided directory (same for importing). It can also be run to import to a remote server so for example, export on a local deployment and import to a remote production deployment.

### CODE REVIEW

**Comment by DiegoPino** [comment]
So cool!! @aksm this looks pretty awesome and thorough! Will test by noon :)

**Comment by DiegoPino** [comment]
@aksm happy to test. Can you give me a short instructional explanation on what/how to test? Thanks so much for your commits!

**Comment by aksm** [comment]
@DiegoPino I added a help option `./import_export.sh -h`. Glad to explain further if it's not clear. I think I still need to expand on that help documentation.

**Comment by DiegoPino** [comment]
Thanks @aksm !!!

**Comment by DiegoPino** [comment]
@aksm I see the lock being committed, then reverted and them committed. Maybe it is not needed here? If so can you simply remove any changes to that file and commit that. Thanks a lot!

**Comment by aksm** [comment]
@DiegoPino Sorry about that! Need to make a permanent sticky to always check upstream changes before pushing.

**Comment by DiegoPino** [comment]
No worries! You fixed It so all good. Thanks!

**Review by DiegoPino — APPROVED** [review]

**Pull request merged**
