### PR TITLE
ISSUE-120(again): Fixes on UpgradeDrupalD9toD10.md

### PR DESCRIPTION
**Pull request by DiegoPino**
@alliomeria these are the ones I found.
A few duplicates 
+ drupal/rdf which needs to be required and then uninstalled at the end
+ removing google client so AMI can install the right version by itself see https://github.com/esmero/ami/blob/0.7.0/composer.json#L25

### CODE REVIEW

**Comment by alliomeria** [comment]
Ok, thank you for opening this issue @DiegoPino

**Comment by DiegoPino** [comment]
@alliomeria if you want/can/merge at your discretion

**Comment by alliomeria** [comment]
Ok great, merged! Sorry for the delay, I wasn't sure if you wanted to add any others.

**Comment by DiegoPino** [comment]
Thanks 🐝 !

**Pull request merged**
